language: node_js
node_js:
    - stable
install:
    - npm install
script:
    - npm run ci
before_script:
    - npm run build
# Update Coveralls
after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
